version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 15.3.0 # Use the latest Xcode version available on CircleCI
    environment:
      FASTLANE_SKIP_UPDATE_CHECK: true
    steps:
      - checkout
      - run:
          name: Setup development environment
          command: |
            chmod +x setup.sh
            ./setup.sh
      - run:
          name: Build and test
          command: |
            make dev
            make build
            make test
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-xcframework:
    macos:
      xcode: 15.3.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build XCFramework
          command: |
            make build-xcframework
      - store_artifacts:
          path: Artifacts/MVVMacroBinary.xcframework
          destination: XCFramework

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - build-xcframework:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
EOF < /dev/null