version: 2.1

orbs:
  snyk: snyk/snyk@2.3.0

jobs:
  build-and-test:
    macos:
      xcode: 16.2.0 # Use Xcode 16.2.0 on CircleCI
    environment:
      FASTLANE_SKIP_UPDATE_CHECK: true
    steps:
      - checkout
      
      # Restore Swift package cache
      - restore_cache:
          keys:
            - spm-cache-v1-{{ checksum "Package.resolved" }}
            - spm-cache-v1-
      
      - run:
          name: Setup development environment
          command: |
            chmod +x setup.sh
            ./setup.sh
      
      - run:
          name: Build and test
          command: |
            make test
            
      # Run Snyk scan to check for vulnerabilities
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          token-variable: SNYK_TOKEN
          additional-arguments: --all-projects
      
      # Save Swift package cache
      - save_cache:
          key: spm-cache-v1-{{ checksum "Package.resolved" }}
          paths:
            - ~/.swiftpm
            - .build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test