version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 16.2.0 # Use Xcode 16.2.0 on CircleCI
    environment:
      FASTLANE_SKIP_UPDATE_CHECK: true
    steps:
      - checkout
      - run:
          name: Setup development environment
          command: |
            chmod +x setup.sh
            ./setup.sh
      - run:
          name: Build and test
          command: |
            make test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test